AWSTemplateFormatVersion: "2010-09-09"
Description: 'EC2 :: Instance Role'

Parameters:
  ArtifactBucketName:
    Type: String
    Description: 'The name of the S3 bucket for artifacts to deploy.'

Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${AWS::StackName}-ec2InstanceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
      - !Ref InstanceRolePolicy

  InstanceRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${AWS::StackName}-S3AccessPolicy
      PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - 's3:*'
              Resource:
                - !Sub 'arn:aws:s3:::${ArtifactBucketName}'
                - !Sub 'arn:aws:s3:::${ArtifactBucketName}/*'

Outputs:
  InstanceRole:
    Description: 'Ec2 instance role ARN'
    Value: !GetAtt InstanceRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-RoleArn
